### PR TITLE
Deyondre branch

### PR DESCRIPTION
**Pull request by DeyondreBeale**
Updated Sam's sidenav and moved card to components. Added Cucumber and Selenium. Can now get date events from the database, close out of the modal when clicking on a calendar date, and move date events by dragging them on calendar.

### CODE REVIEW

**Review by kileader — CHANGES_REQUESTED** [review]
The front end looks good I think, but someone else more familiar with it should review it.

The feature files aren't java and should be in test/resources, but they look well written.
HomePageTest should not be there, but I understand that it's useful just to get started.
For organization, I like having all the cucumber test stuff in its own package, I called mine webapp, but it's not necessary.
It might be better to consolidate the runners into one or a few runners, especially if a certain feature file crosses multiple pages, and that would just need glue to be only { "com.revature.steps" } (or "com.revature.webapp.steps") .

**Review by DeyondreBeale — COMMENTED** [review]
My original plan was to have the tests in a test/resource folder, but I didn't see one and didn't know how to create one. Also, I put cucumber steps, runners, and features in different packages because that's how Ryan had them and it could be easier to read. I figured we could just run the runners package to handle all the runners as well.

**Comment by kileader** [comment]
Ok, all that is fine, just thought I'd put in my opinion. But moving specifically the feature files folder since feature files aren't .java to test/resources I think should be done. Then the @CucumberOptions should be : features = "src/test/resources/features" or similar

**Review by kileader — APPROVED** [review]
Thanks Deyondre

**Pull request merged**
